baseURL: "https://digitalgarden.justinpatedevelops.com/"
title: "Justin Pate's Digital Garden"
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  # env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: "Justin Pate's Digital Garden"
  description: "A place to share my interests, hobbies, and learnings."
  keywords: [Digital, Garden, Vanity]
  author: Justin Pate
  # author: ["Me", "You"] # multiple authors
  # images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowAllPagesInArchive: true
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    # favicon: "<link / abs url>"
    # favicon16x16: "<link / abs url>"
    # favicon32x32: "<link / abs url>"
    # apple_touch_icon: "<link / abs url>"
    # safari_pinned_tab: "<link / abs url>"
    # noun_human_mind: /static/images/noun-human-mind-4125615.png

  label:
    text: "Justin Pate's Digital Garden"
    # icon: /static/images/noun-human-mind-4125615.png
    # iconHeight: 35

  # profile-mode
  # profileMode:
  #   enabled: false # needs to be explicitly set
  #   title: ExampleSite
  #   subtitle: "This is subtitle"
  #   imageUrl: "<img location>"
  #   imageWidth: 120
  #   imageHeight: 120
  #   imageTitle: my image
  #   buttons:
  #     - name: Posts
  #       url: posts
  #     - name: Tags
  #       url: tags

  # home-info mode
  homeInfoParams:
        Title: "Justin Pate's Digital Garden"
        Content: >
            Welcome to my [digital garden](/digital-garden/my-definition-of-a-digital-garden/). 
            If you'd like to get started poking around my content, [Categories](/categories/) and 
            [Tags](/tags/) are a great place to start. Feel free to message me on [Twitter](https://twitter.com/JustinMP8) if you'd like 
            to discuss anything you see here!

  socialIcons:
    - name: twitter
      url: "https://twitter.com/JustinMP8"
    - name: linkedin
      url: "https://www.linkedin.com/in/justinp8/"
    - name: github
      url: "https://github.com/JustinP8"
    - name: stackoverflow
      url: "https://stackoverflow.com/users/178207/justinp8"   

  # analytics:
  #   google:
  #     SiteVerificationTag: "XYZabc"
  #   bing:
  #     SiteVerificationTag: "XYZabc"
  #   yandex:
  #     SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # editPost:
  #   URL: "https://github.com/<path_to_repo>/content"
  #   Text: "Suggest Changes" # edit text
  #   appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

taxonomies:
  category: categories
  tag: tags
  series: series

menu:
  main:
    # - identifier: series
    #   name: series
    #   url: /series/
    #   weight: 5
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 30
    # - identifier: example
    #   name: example.org
    #   url: https://example.org
    #   weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai